blindnet-io/privacy-components-web

.github/workflows/release.yml
package.json

add missing "bundle" task and fix the related script in order to have a `build/` directory to release.

ci: fix release workflows

---

.github/workflows/release.yml

only deploy the documentation and demos to Github pages when releasing
a "final" version (i.e. on main branch)

ci: stable docs only

---

packages/core/import-map.json
packages/core/package.json
packages/core/src/hello-world/hello-world.ts

For now, the core library is just an empty placeholder for future refactorings.
The lit dependency was only added for testing.

chore(@blindnet/core): remove dependency to lit

---

.github/workflows/release.yml
lerna.json
package.json

- use conventionalCommits by default
- [ignore `lerna changed`](https://github.com/lerna/lerna/tree/main/commands/version#--force-publish) when bumping versions in main (bumping the version of all packages, including the unchanged ones, to enforce version numbers are always in sync)
- remove the version number of the root package (as it [isn't included in lerna version by default](https://github.com/lerna/lerna/issues/2879) and no workaround seems useful)

build: update lerna versionning

---

.github/workflows/release.yml

Avoid committing releases from the develop branch has it makes the changelog confusing.
Unfortunately, I didn't find any solution to increment the beta version number without commits for now, so I used the last commit hash instead (same as for PRs).

ci: don't commit beta releases

---

.github/workflows/release.yml

use the canary option to make sure lerna doesn't try to release a
conventional version number

ci: beta releases are now canary releases

---

.github/semantic.yml

Semantic-prs is only required for PRs targetting the develop branch.
It will fail for release PRs (targetting the main branch), but you can just ignore it.

ci: disablow merge and revert commits on PRs

---

demos/devkit-simple-tutorial/index.html
demos/devkit-simple-tutorial/src/DevkitSimpleTutorial.js
demos/devkit-simple-tutorial/src/views/BackOffice.js
demos/devkit-simple-tutorial/src/views/DCI.js
demos/devkit-simple-tutorial/src/views/Home.js
demos/devkit-simple-tutorial/web-dev-server.config.mjs

update the base href, related web-dev-server configuration, and links in the application to make it work with our current CD environment (https://blindnet-io.github.io/privacy-components-web/demos/devkit-simple-tutorial/)

fix(@blindnet-demos/devkit-simple-tutorial): base url

---

.github/workflows/release.yml

define a git remote so Lerna can push to the main branch (apparently not correctly handled by actions/checkout)
> **Warning**
>
> The issue could also be linked to Lerna not properly handling push. In that case, we should push manually instead (add the `--no-push` argument to Lerna version and use `git push --follow-tags` instead).
see https://github.com/blindnet-io/privacy-components-web/runs/8202788472?check_suite_focus=true#step:8:13 compared to https://github.com/blindnet-io/privacy-components-web/runs/7797305609 (https://github.com/blindnet-io/privacy-components-web/commit/ee573dfe048c80e04623bc16bf437060eb19494c#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R53)

ci: set git remote origin

---

.github/workflows/release.yml

as release on main creates a new commit, we need to merge this commit back into develop so the new version is taken into account when releasing new beta versions

ci: merge main into develop after release

---

.github/workflows/release.yml

Lerna seems to have several issues when trying to push a branch after a release so we'll push directly with git instead.
see #101 and https://github.com/blindnet-io/privacy-components-web/runs/8225337458#step:8:14

ci: don't use lerna to push branch

---

.github/workflows/release.yml

Well, apparently, actions/checkout doesn't properly set the branch upstream either, so let's just directly define that.

ci: git push upstream

---

.github/workflows/release.yml

After checking out the origin/develop branch, git is in a detached head state and doesn't know what to push, so we need to specify we want to push HEAD to origin/develop.

ci: fix merge of main to develop after release

---

package.json

Rollup fails to rewrite raw build files when using watch mode, while bundled files are overwritten correctly. This seems to be linked to Rollup having issues when running watch mode with several build configs. As a workaround, the npm watch script now only runs the first "raw" build in the configuration (the one for npm). This should be enough as demos and storybook only use this build, while the bundles are only used in the static demo (which require rerunning the bundle script anyway) or when loading them from the unpkgr CDN (and well, we can't have a watch on this).

build: only build raw on watch

---

demos/static/index.html

the bundle script copies the dist/ folder of every package, not the root one, contrarily to npm pack (hence the different paths in unpkg and local URLs)

fix(@blindnet-demos/static): wrong script URLs

---

demos/devkit-simple-tutorial/index.html
demos/devkit-simple-tutorial/web-dev-server.config.mjs

removing the repository name from the base href as we are moving from the automatically associated GitHub pages URL to pc4w.blindnet.dev

chore(@blindnet-demos/devkit-simple-tutorial): update base href

---

demos/devkit-simple-tutorial/src/views/Form.js
packages/prci/src/BldnPrivRequest.ts
packages/prci/src/utils/privacy-request-api.ts

This is a change for the demo. ACCESS request should return data about a user who submitted the prizes form.
The user id (email) is stored and retrieved from the local storage.

chore(@blindnet/prci): retrieve user from local storage 

---

demos/devkit-simple-tutorial/package.json
demos/devkit-simple-tutorial/rollup.config.js
rollup.config.js
tasks/rollup-base-config.js

fix `yarn typecheck` by disabling type-checking on rollup config files,
as they depend on way too many packages with buggy type definition and
configuration, and set the devkit-simple-tutorial as an ESM project to
avoid errors when using packages with ESM only (like @open-wc/testing)
and browser / ESM specific things like `import.meta`

build: fix typeschecking

---

demos/devkit-simple-tutorial/src/views/Login.js
demos/devkit-simple-tutorial/src/views/Privacy.js

This way we can add claims to the access token which can be verified on the server.

feat(@blindnet-demos/devkit-simple-tutorial) add audience option to auth0 client

---

demos/devkit-simple-tutorial/src/views/Privacy.js

Proposing alternative wordings to make it clear that users don't have an account here, they only verify their e-mail to be able to make a personalized reuqest.
@jboileau99 pleaste test if it works and merge if you accept the change

ditch the login/logout wordings

---

package.json
packages/prci/src/bldn-priv-request.ts
packages/prci/src/bldn-request-builder.ts
packages/prci/src/bldn-submitted-requests.ts
tasks/build-fix-locales.js

replaces `lit` and `lit-localize` imports in generated translation files with their CDN urls, mimicking the functionality of [import maps](https://www.digitalocean.com/community/tutorials/how-to-dynamically-import-javascript-with-import-maps).

fix: map imports for runtime localization

---

packages/prci/src/bldn-priv-request.ts

Adds a listener for the `bldn-priv-request-api-token:set` event to the PRCI component

feat(@blindnet/prci): set api token via event
