demo/index.html, src/ActionItem.ts, src/BldnPrivRequest.ts, src/DemandActionMenu.ts, src/DemandBuilder.ts, src/DemandBuilderDropdownElement.ts, src/DemandBuilderSidebar.ts, src/DemandBuilderSidebarButton.ts, src/DemandBuilderTextElement.ts, src/priv.ts, src/utils.ts, stories/index.stories.ts
Combing these branches, draft pr to main in #3
=> Demand builder

demo/index.html
https://blindnet-io.github.io/privacy-components-web/demo/ Should now work properly
=> fix issue with demo importing bare module

.github/semantic.yml
enforce Conventional Commits specs on PRs according to our CONTRIBUTING
guide (see https://github.com/Ezard/semantic-prs)
=> build: add semantic-prs configuration

package.json
=> fix: preinstall command on windows

packages/prci/src/BldnPrivRequest.ts
Updating the endpoint and data subject id to fit https://devkit-pce-staging.azurewebsites.net/swagger/
=> chore(@blindnet/prci): update call to PCE

packages/prci/src/BldnPrivRequest.ts, packages/prci/src/demand-forms/TransparencyForm.ts, packages/prci/src/models/demand.ts, packages/prci/src/models/privacy-response.ts, packages/prci/src/utils/privacy-request-api.ts
Fixes provenance and additional message in transparency form and sends privacy requests to api
=> Fix transparency form and send requests

.github/semantic.yml, CONTRIBUTING.md, demo/index.html, packages/dci/README.md, packages/dci/package.json, packages/dci/src/DataConsumerInterface.ts, packages/dci/src/index.ts, packages/dci/test/dci.test.ts, packages/prci/README.md, packages/prci/test/prci.test.ts
Add configuration and demo to quickstart Data Consumer Interface development.
=> Init a new @blindnet/dci package

packages/prci/src/utils/privacy-request-api.ts
When privacy scope restrictions are added for all possible data categories, simply remove all restrictions
=> chore(@blindnet/prci): simplify privacy scope restriction

packages/prci/src/ActionItem.ts
Decrease the font size so text fits in the menu buttons for the demo. Forgot to include this in #75.
=> style: decrease menu font size

packages/prci/src/StatusView.ts, packages/prci/src/StatusViewItem.ts
Eventually we will want to dynamically set the file extension as data will not always be a JSON, as it is for the demo.
=> chore(@blindnet/prci): demand data file extension and reload

packages/dci/src/RequestsListItem.ts, packages/dci/src/utils/data-consumer-api.ts, packages/prci/src/StatusView.ts, packages/prci/src/StatusViewItem.ts, packages/prci/src/demand-forms/TransparencyForm.ts, packages/prci/src/utils/dictionary.ts, packages/prci/src/utils/utils.ts
Includes changes for #89, #90, and #96.
=> chore: PRCI and DCI updates for demo

demos/devkit-simple-tutorial/src/views/Form.js, packages/core/src/components/SlottedDropdown.ts, packages/prci/src/BldnPrivRequest.ts, packages/prci/src/ReviewView.ts, packages/prci/src/StatusViewItem.ts, packages/prci/src/demand-forms/DemandForm.ts, packages/prci/src/demand-forms/MultiDemandForm.ts, packages/prci/src/demand-forms/RevokeConsentForm.ts, packages/prci/src/demand-forms/TransparencyForm.ts, packages/prci/src/utils/conf.ts, packages/prci/src/utils/utils.ts, stories/index.stories.ts
Includes updated demo form which gives consent that can then be revoked in the prci
=> feat(@blindnet/prci): revoke consent requests

README.md
=> docs: add demo link to README

packages/dci/src/RequestsListItem.ts
=> chore(@blindnet/dci): show dsid in requests to process list

localization/translations/fr.xlf, packages/prci/src/StatusViewItem.ts, packages/prci/src/utils/dictionary.ts, packages/prci/src/utils/privacy-request-api.ts
cancelled requests have a different status box and are also reflected in the DCI
=> feat(@blindnet/prci): cancel privacy requests

demos/devkit-simple-tutorial/src/DevkitSimpleTutorial.js, packages/prci/src/styles.ts
Quick fix to improve the responsiveness of the PRCI and the devkit-simple-tutorial demo.
Should partially solve https://github.com/blindnet-io/product-management/issues/956.
The "it doesn't work on mobile" part will need more attention (see https://github.com/blindnet-io/privacy-components-web/issues/153).
=> fix: responsiveness

package.json, tsconfig.json
following our discussion on Slack regarding https://github.com/blindnet-io/privacy-components-web/actions/runs/3218721008/jobs/5263237068
=> build: fix typings

demos/devkit-simple-tutorial/src/views/Form.js, demos/devkit-simple-tutorial/src/views/Login.js, demos/devkit-simple-tutorial/src/views/Privacy.js
- Fixes issue with demo redirection
=> chore: fix demo redirection

packages/core/src/computation/computation-api.ts, packages/core/src/configuration/core-configuration-mixin.ts, packages/prci/src/StatusView.ts
Only transparency requests can be made without an auth header
=> fix(@blindnet/prci): enforce an auth header for most requests

demos/devkit-simple-tutorial/src/views/Form.js, demos/devkit-simple-tutorial/src/views/Login.js
Switches to unauthenticated consent in demo
=> feat(@blindnet-demos/devkit-simple-tutorial): demo consent

demos/devkit-simple-tutorial/src/DevkitSimpleTutorial.js, demos/devkit-simple-tutorial/src/views/Login.js, demos/devkit-simple-tutorial/src/views/Privacy.js
Contains UI and configuration updates for the demo
=> release: next minor version

demos/devkit-simple-tutorial/src/views/Home.js, packages/prci/src/bldn-privacy-scope-picker.ts, packages/prci/src/bldn-request-builder.ts
@Clementinev Fixes for the bugs mentioned in each commit message :smile:
=> chore(@blindnet/prci): fix bugs

demos/devkit-simple-tutorial/src/views/Privacy.js, packages/prci/src/bldn-request-status.ts
crawl through shadow roots to find and click the refresh button every 3 seconds
=> chore(@blindnet/prci): auto click the refresh request button in demo

packages/prci/src/bldn-request-builder.ts
Will emit bldn-request-builder:request-created events containing request details
=> feat(@blindnet/prci): use PRCI without token
